### ISSUE TITLE
最好支持下老版本 Python

### ISSUE THREAD

**Issue by 2044-space-elevator** [Rickyxrc/at-cli#11]
Python3.11 版本太高了，很多人没有

@Rickyxrc

**Comment by Rickyxrc** [comment]
> This package needs python3.11, but i only have python3.10. How about support old python? 
> 
> 
> 
> @Rickyxrc 

请提供该应用能运行的最低python版本

**Comment by 2044-space-elevator** [comment]
> > This package needs python3.11, but i only have python3.10. How about support old python?
> > @Rickyxrc
> 
> 请提供该应用能运行的最低python版本

Python3.11，既然 owner 用中文我也不忌讳了。

~~事实证明如果想支持多版本的话兼容性越强越好，比如 python3.5 或 python3.6~~

**Comment by Rickyxrc** [comment]
> > > This package needs python3.11, but i only have python3.10. How about support old python?
> 
> > > @Rickyxrc
> 
> > 
> 
> > 请提供该应用能运行的最低python版本
> 
> 
> 
> Python3.11。
> 

我的意思是，通过不修改源代码，仅仅忽略版本限制，能运行的最低版本

> 
> ~~事实证明如果想支持多版本的话兼容性越强越好，比如 python3.5 或 python3.6~~

降级可能会导致依赖的pypi包过时，有安全问题等等。

**Comment by 2044-space-elevator** [comment]
> > > > This package needs python3.11, but i only have python3.10. How about support old python?
> > 
> > 
> > > > @Rickyxrc
> > 
> > 
> > > 
> > 
> > 
> > > 请提供该应用能运行的最低python版本
> > 
> > 
> > Python3.11。
> 
> 我的意思是，通过不修改源代码，仅仅忽略版本限制，能运行的最低版本
> 
> > ~事实证明如果想支持多版本的话兼容性越强越好，比如 python3.5 或 python3.6~
> 
> 降级可能会导致依赖的pypi包过时，有安全问题等等。

能再详细说明一下吗？是指直接 clone 跑源码还是 pip 能下载的最低版本？

**Comment by Rickyxrc** [comment]
> 能再详细说明一下吗？是指直接 clone 跑源码还是 pip 能下载的最低版本？

pip上能下载的版本是指定在 pyproject.toml 里面的，你可能需要 clone 下来测一下

**Comment by 2044-space-elevator** [comment]
> > 能再详细说明一下吗？是指直接 clone 跑源码还是 pip 能下载的最低版本？
> 
> pip上能下载的版本是指定在 pyproject.toml 里面的，你可能需要 clone 下来测一下

clone 前几天测过了，直接跑 run.sh 是没有任何问题的，但是显然这样对用户不友好。

**Comment by Rickyxrc** [comment]
> > > 能再详细说明一下吗？是指直接 clone 跑源码还是 pip 能下载的最低版本？
> 
> > 
> 
> > pip上能下载的版本是指定在 pyproject.toml 里面的，你可能需要 clone 下来测一下
> 
> 
> 
> clone 前几天测过了，直接跑 run.sh 是没有任何问题的，但是显然这样对用户不友好。

我的意思是，用不同的python版本测，看能不能跑，依赖有没有降级

**Comment by Rickyxrc** [comment]
已测试，在其他低于python3.11的版本运行均会导致依赖降级。

**Comment by 2044-space-elevator** [comment]
> 已测试，在其他低于python3.11的版本运行均会导致依赖降级。

指定依赖呢？

**Comment by Rickyxrc** [comment]
不急，降的不多可以降

**Comment by immccn123** [comment]
由于 Python 3.6 破坏了依赖链，现更改到 `python >= 3.9`。
