### ISSUE TITLE
一个 contest 里有交互题会报错

### ISSUE THREAD

**Issue by 2044-space-elevator** [Rickyxrc/at-cli#12]
因为暂时上不了 pip，所以我直接 python -m atcodercli 的。

command log:
```
C:\Users\S.X.Y\Desktop\at-cli>python -m atcodercli contest race abc337
No config file found under ~/.config/atcli/config.yaml
created a null config at C:\Users\S.X.Y\.config\atcli\config.yaml
initialized empty problem.yaml, now use "atcli problem add"
add problem abc337_a
add problem abc337_b
add problem abc337_c
add problem abc337_d
add problem abc337_e
Traceback (most recent call last):
  File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\S.X.Y\Desktop\at-cli\atcodercli\__main__.py", line 193, in <module>
    dispatch_args()
  File "C:\Users\S.X.Y\Desktop\at-cli\atcodercli\__main__.py", line 182, in dispatch_args
    handleInitContest(console, arg)
  File "C:\Users\S.X.Y\Desktop\at-cli\atcodercli\commands\initcontest.py", line 24, in handle
    add_problem(console, arg.contest_id, problemId)
  File "C:\Users\S.X.Y\Desktop\at-cli\atcodercli\commands\addproblem.py", line 28, in add_problem
    id = int(re.findall("Sample Input (\d+)", stat_str.string)[0])
IndexError: list index out of range

C:\Users\S.X.Y\Desktop\at-cli>
```
而 abc337_e 是一道交互题：

![图片](https://github.com/Rickyxrc/at-cli/assets/139243439/8429f4fd-220b-435a-9715-00de688538ee)

输入输出形式如下：

![图片](https://github.com/Rickyxrc/at-cli/assets/139243439/9e6dcc75-2294-4b35-ae7c-6ee97f4592e1)

注意到报错代码：

![图片](https://github.com/Rickyxrc/at-cli/assets/139243439/60a4ba54-f32a-4ab7-891e-8274ab0cccac)

判断形式很简陋，就是判断有没有一个 h3 包含 Sample Input，但是交互题的样例里写的是 Sample Input/Output，并用表格表示，所以报错。

**Comment by 2044-space-elevator** [comment]
@Rickyxrc 

建议添加纠错代码，遇到交互题自动跳过。

**Comment by Rickyxrc** [comment]
> @Rickyxrc
> 
> 建议添加纠错代码，遇到交互题自动跳过。

问题可以复现，正在修复。

**Comment by Rickyxrc** [comment]
Pypi  包 0.3.6 已发布，请在本地测试一下，看是否解决了问题。

**Comment by 2044-space-elevator** [comment]
> Pypi 包 0.3.6 已发布，请在本地测试一下，看是否解决了问题。

虽然但是好像又有bug了：

```
C:\Users\S.X.Y\Desktop>python -m atcodercli contest race abc337
initialized empty problem.yaml, now use "atcli problem add"
add problem abc337_a
add problem abc337_b
add problem abc337_c
add problem abc337_d
add problem abc337_e
Failed when parsing abc337_e.
This problem maybe a interactive problem.
If not, this behavior might not net your expectation, please open a issue and let me know.
add problem abc337_f
add problem abc337_g
Traceback (most recent call last):
  File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\site-packages\atcodercli\__main__.py", line 193, in <module>
    dispatch_args()
  File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\site-packages\atcodercli\__main__.py", line 182, in dispatch_args
    handleInitContest(console, arg)
  File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\site-packages\atcodercli\commands\initcontest.py", line 27, in handle
    template_name:str = config.dat['template']['default']
TypeError: 'NoneType' object is not subscriptable

C:\Users\S.X.Y\Desktop>
```

**Comment by Rickyxrc** [comment]
> > Pypi 包 0.3.6 已发布，请在本地测试一下，看是否解决了问题。
> 
> 
> 
> 虽然但是好像又有bug了：
> 
> 
> 
> ```
> 
> C:\Users\S.X.Y\Desktop>python -m atcodercli contest race abc337
> 
> initialized empty problem.yaml, now use "atcli problem add"
> 
> add problem abc337_a
> 
> add problem abc337_b
> 
> add problem abc337_c
> 
> add problem abc337_d
> 
> add problem abc337_e
> 
> Failed when parsing abc337_e.
> 
> This problem maybe a interactive problem.
> 
> If not, this behavior might not net your expectation, please open a issue and let me know.
> 
> add problem abc337_f
> 
> add problem abc337_g
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
> 
>     return _run_code(code, main_globals, None,
> 
>   File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
> 
>     exec(code, run_globals)
> 
>   File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\site-packages\atcodercli\__main__.py", line 193, in <module>
> 
>     dispatch_args()
> 
>   File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\site-packages\atcodercli\__main__.py", line 182, in dispatch_args
> 
>     handleInitContest(console, arg)
> 
>   File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\site-packages\atcodercli\commands\initcontest.py", line 27, in handle
> 
>     template_name:str = config.dat['template']['default']
> 
> TypeError: 'NoneType' object is not subscriptable
> 
> 
> 
> C:\Users\S.X.Y\Desktop>
> 
> ```

这是程序的预期行为。

**Comment by Rickyxrc** [comment]
当我没说

**Comment by 2044-space-elevator** [comment]
![图片](https://github.com/Rickyxrc/at-cli/assets/139243439/d6c6d8af-2b3f-4539-852c-c701669424c1)

哈哈 Rickyxrc 真可爱。

**Comment by Rickyxrc** [comment]
> > Pypi 包 0.3.6 已发布，请在本地测试一下，看是否解决了问题。
> 
> 虽然但是好像又有bug了：
> 
> ```
> C:\Users\S.X.Y\Desktop>python -m atcodercli contest race abc337
> initialized empty problem.yaml, now use "atcli problem add"
> add problem abc337_a
> add problem abc337_b
> add problem abc337_c
> add problem abc337_d
> add problem abc337_e
> Failed when parsing abc337_e.
> This problem maybe a interactive problem.
> If not, this behavior might not net your expectation, please open a issue and let me know.
> add problem abc337_f
> add problem abc337_g
> Traceback (most recent call last):
>   File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\site-packages\atcodercli\__main__.py", line 193, in <module>
>     dispatch_args()
>   File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\site-packages\atcodercli\__main__.py", line 182, in dispatch_args
>     handleInitContest(console, arg)
>   File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\site-packages\atcodercli\commands\initcontest.py", line 27, in handle
>     template_name:str = config.dat['template']['default']
> TypeError: 'NoneType' object is not subscriptable
> 
> C:\Users\S.X.Y\Desktop>
> ```

你没有设置默认模板和模板代码，我先加异常处理，稍后补文档。

**Comment by 2044-space-elevator** [comment]
> > > Pypi 包 0.3.6 已发布，请在本地测试一下，看是否解决了问题。
> > 
> > 
> > 虽然但是好像又有bug了：
> > ```
> > C:\Users\S.X.Y\Desktop>python -m atcodercli contest race abc337
> > initialized empty problem.yaml, now use "atcli problem add"
> > add problem abc337_a
> > add problem abc337_b
> > add problem abc337_c
> > add problem abc337_d
> > add problem abc337_e
> > Failed when parsing abc337_e.
> > This problem maybe a interactive problem.
> > If not, this behavior might not net your expectation, please open a issue and let me know.
> > add problem abc337_f
> > add problem abc337_g
> > Traceback (most recent call last):
> >   File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
> >     return _run_code(code, main_globals, None,
> >   File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
> >     exec(code, run_globals)
> >   File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\site-packages\atcodercli\__main__.py", line 193, in <module>
> >     dispatch_args()
> >   File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\site-packages\atcodercli\__main__.py", line 182, in dispatch_args
> >     handleInitContest(console, arg)
> >   File "C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\lib\site-packages\atcodercli\commands\initcontest.py", line 27, in handle
> >     template_name:str = config.dat['template']['default']
> > TypeError: 'NoneType' object is not subscriptable
> > 
> > C:\Users\S.X.Y\Desktop>
> > ```
> 
> 你没有设置默认模板和模板代码，我先加异常处理，稍后补文档。

好的……

**Comment by Rickyxrc** [comment]
已经发布 v0.3.7，请看看问题是否解决。

**Comment by 2044-space-elevator** [comment]
> 已经发布 v0.3.7，请看看问题是否解决。

已解决，thx，不过template怎么用？建议 readme 加一下。

**Comment by Rickyxrc** [comment]
> > 已经发布 v0.3.7，请看看问题是否解决。
> 
> 
> 
> 已解决，thx，不过template怎么用？建议 readme 加一下。

先看config.sample.yaml吧，我这调考查成绩emo去了。
