### ISSUE TITLE
Windows 里pip包中文无法使用

### ISSUE THREAD

**Issue by 2044-space-elevator** [Rickyxrc/at-cli#33]
![图片](https://github.com/Rickyxrc/at-cli/assets/139243439/cd216c0a-e0b0-463f-9196-e583137942dc)

控制端输出：
![图片](https://github.com/Rickyxrc/at-cli/assets/139243439/56bdce7b-194d-48b4-bb67-f9318eea89b1)

我设置好了环境变量后还关闭并重开了 Terminal。

请问是要重启吗？

**Comment by 2044-space-elevator** [comment]
@Rickyxrc

**Comment by Rickyxrc** [comment]
> @Rickyxrc 

这个是针对linux设计的，语言切换在__init__.py里面，没在windows上测试过

**Comment by Rickyxrc** [comment]
@2044-space-elevator #34 能解决您的问题吗？

**Comment by 2044-space-elevator** [comment]
> @2044-space-elevator #34 能解决您的问题吗？

![图片](https://github.com/Rickyxrc/at-cli/assets/139243439/d3d42d5a-5132-457c-8a66-fea749efac28)

我直接改了源代码，依然没有效果。

**Comment by Rickyxrc** [comment]
> 我直接改了源代码，依然没有效果。

主要是我手上没有可以用于测试的 windows 设备，您能提交这个 PR 吗？

**Comment by 2044-space-elevator** [comment]
> @2044-space-elevator #34 能解决您的问题吗？

原因可能不是在 LANG 变量里，对比输出了一下（加了一个 `print(LANG)`）：

改后

```
C:\Users\S.X.Y\Desktop\汪昱帆\01 Programming\at-cli>python -m atcodercli
zh_CN
usage: atcli [-h] {login,me,result,problem,contest,template} ...
atcli: error: the following arguments are required: command
```
改前：

```
C:\Users\S.X.Y\Desktop\汪昱帆\01 Programming\at-cli>python -m atcodercli
zh_CN
```

而且删去 try expect 会触发错误提示。



> > 我直接改了源代码，依然没有效果。
> 
> 主要是我手上没有可以用于测试的 windows 设备，您能提交这个 PR 吗？

尽我所能吧，我试一试（尽管可能会去世）。

**Comment by immccn123** [comment]
@2044-space-elevator 您是源码运行还是走的 `pip` 安装？

**Comment by immccn123** [comment]
如果是源码运行的话，请使用 `poetry` 进行项目管理而不是哪里少了什么 `module` 装什么。

请检查 `atcodercli/locales/zh_CN/LC_MESSAGES/atcodercli.mo`（注意不是 `.po`）文件是否存在。若不存在，请执行 `scripts/build-mo.py` 生成可供程序读取的 `.mo` 本地化文件。

**Comment by immccn123** [comment]
@Rickyxrc `locale.getdefaultlocale()` 在 Python 3.11 中已经 deprecated。请考虑修复。

**Comment by immccn123** [comment]
另外，在我的设备上试过了，Windows 下不手动设置环境变量仍然可以正确识别语言。

**Comment by 2044-space-elevator** [comment]
![图片](https://github.com/Rickyxrc/at-cli/assets/139243439/6b957d4b-84fb-400d-b483-3bb02f407c00)

pip 重装也用不了中文……

我依赖有问题吗？还是我对 Py 孤陋寡闻了？

**Comment by immccn123** [comment]
如果 pip 用不了的话，烦请 @rickyxrc 看一下打包情况。

**Comment by Rickyxrc** [comment]
我严重怀疑pypi打包的whl文件里面应该是有mo的，还是把build-mo放到hook里面吧（
等我下课紧急开个PR

**Comment by Rickyxrc** [comment]
解包了，没有。
似乎这个是看gitignore的

**Comment by Rickyxrc** [comment]
@immccn123 @2044-space-elevator #49 能否解决您的问题呢？pypi包版本0.5.4-beta0

**Comment by immccn123** [comment]
```python
Python 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getlocale()[0]
'Chinese (Simplified)_China'
>>> locale.getdefaultlocale()[0]
<stdin>:1: DeprecationWarning: 'locale.getdefaultlocale' is deprecated and slated for removal in Python 3.15. Use setlocale(), getencoding() and getlocale() instead.
'zh_CN'
```

🤔

**Comment by Rickyxrc** [comment]
经测试，alpine无法使用目前最新正式版0.5.4

**Comment by Rickyxrc** [comment]
经测试，alpine python3.9使用beta0已经可以正常运行并输出翻译内容。
![image](https://github.com/Rickyxrc/at-cli/assets/81732554/f058a2e3-0f6d-43f5-85c2-46b0c4ab875e)

**Comment by 2044-space-elevator** [comment]
> @immccn123 @2044-space-elevator #49 能否解决您的问题呢？pypi包版本0.5.4b0

```cmd
Microsoft Windows [Version 10.0.19045.3930]
(c) Microsoft Corporation。保留所有权利。

C:\Users\S.X.Y>pip3.10 install at-cli==0.5.4b0
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement at-cli==0.5.4b0 (from versions: none)
ERROR: No matching distribution found for at-cli==0.5.4b0

C:\Users\S.X.Y>pip3.10 install atcodercli==0.5.4b0
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting atcodercli==0.5.4b0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/43/74/6716d5a1713d5862dfa7363ffc2eca19ecf93fc570b543681b3b10e6c4ad/atcodercli-0.5.4b0-py3-none-any.whl (26 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.12.3 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from atcodercli==0.5.4b0) (4.12.3)
Requirement already satisfied: pyyaml<7.0.0,>=6.0.1 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from atcodercli==0.5.4b0) (6.0.1)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from atcodercli==0.5.4b0) (2.31.0)
Requirement already satisfied: rich<14.0.0,>=13.7.0 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from atcodercli==0.5.4b0) (13.7.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4<5.0.0,>=4.12.3->atcodercli==0.5.4b0) (2.5)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.31.0->atcodercli==0.5.4b0) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.31.0->atcodercli==0.5.4b0) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.31.0->atcodercli==0.5.4b0) (1.26.17)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.31.0->atcodercli==0.5.4b0) (2022.6.15)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from rich<14.0.0,>=13.7.0->atcodercli==0.5.4b0) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from rich<14.0.0,>=13.7.0->atcodercli==0.5.4b0) (2.16.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from markdown-it-py>=2.2.0->rich<14.0.0,>=13.7.0->atcodercli==0.5.4b0) (0.1.2)
Installing collected packages: atcodercli
  Attempting uninstall: atcodercli
    Found existing installation: atcodercli 0.5.3
    Uninstalling atcodercli-0.5.3:
      Successfully uninstalled atcodercli-0.5.3
Successfully installed atcodercli-0.5.4b0

C:\Users\S.X.Y>python -m at-cli
C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\python.exe: No module named at-cli

C:\Users\S.X.Y>python -m atcodercli
usage: atcli [-h] {login,me,result,problem,contest,template} ...
atcli: error: the following arguments are required: command

C:\Users\S.X.Y>
```

事实证明不能。

**Comment by immccn123** [comment]
> > @immccn123 @2044-space-elevator #49 能否解决您的问题呢？pypi包版本0.5.4b0
> 
> ```batchfile
> Microsoft Windows [Version 10.0.19045.3930]
> (c) Microsoft Corporation。保留所有权利。
> 
> C:\Users\S.X.Y>pip3.10 install at-cli==0.5.4b0
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
> ERROR: Could not find a version that satisfies the requirement at-cli==0.5.4b0 (from versions: none)
> ERROR: No matching distribution found for at-cli==0.5.4b0
> 
> C:\Users\S.X.Y>pip3.10 install atcodercli==0.5.4b0
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
> Collecting atcodercli==0.5.4b0
>   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/43/74/6716d5a1713d5862dfa7363ffc2eca19ecf93fc570b543681b3b10e6c4ad/atcodercli-0.5.4b0-py3-none-any.whl (26 kB)
> Requirement already satisfied: beautifulsoup4<5.0.0,>=4.12.3 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from atcodercli==0.5.4b0) (4.12.3)
> Requirement already satisfied: pyyaml<7.0.0,>=6.0.1 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from atcodercli==0.5.4b0) (6.0.1)
> Requirement already satisfied: requests<3.0.0,>=2.31.0 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from atcodercli==0.5.4b0) (2.31.0)
> Requirement already satisfied: rich<14.0.0,>=13.7.0 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from atcodercli==0.5.4b0) (13.7.0)
> Requirement already satisfied: soupsieve>1.2 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4<5.0.0,>=4.12.3->atcodercli==0.5.4b0) (2.5)
> Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.31.0->atcodercli==0.5.4b0) (2.0.12)
> Requirement already satisfied: idna<4,>=2.5 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.31.0->atcodercli==0.5.4b0) (3.3)
> Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.31.0->atcodercli==0.5.4b0) (1.26.17)
> Requirement already satisfied: certifi>=2017.4.17 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.31.0->atcodercli==0.5.4b0) (2022.6.15)
> Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from rich<14.0.0,>=13.7.0->atcodercli==0.5.4b0) (3.0.0)
> Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from rich<14.0.0,>=13.7.0->atcodercli==0.5.4b0) (2.16.1)
> Requirement already satisfied: mdurl~=0.1 in c:\users\s.x.y\appdata\local\programs\python\python310\lib\site-packages (from markdown-it-py>=2.2.0->rich<14.0.0,>=13.7.0->atcodercli==0.5.4b0) (0.1.2)
> Installing collected packages: atcodercli
>   Attempting uninstall: atcodercli
>     Found existing installation: atcodercli 0.5.3
>     Uninstalling atcodercli-0.5.3:
>       Successfully uninstalled atcodercli-0.5.3
> Successfully installed atcodercli-0.5.4b0
> 
> C:\Users\S.X.Y>python -m at-cli
> C:\Users\S.X.Y\AppData\Local\Programs\Python\Python310\python.exe: No module named at-cli
> 
> C:\Users\S.X.Y>python -m atcodercli
> usage: atcli [-h] {login,me,result,problem,contest,template} ...
> atcli: error: the following arguments are required: command
> 
> C:\Users\S.X.Y>
> ```
> 
> 事实证明不能。

呃，现在这个 command not found 界面是没有做本地化的（

**Comment by Rickyxrc** [comment]
> ```python
> ```python
> Python 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import locale
> >>> locale.getlocale()[0]
> 'Chinese (Simplified)_China'
> >>> locale.getdefaultlocale()[0]
> <stdin>:1: DeprecationWarning: 'locale.getdefaultlocale' is deprecated and slated for removal in Python 3.15. Use setlocale(), getencoding() and getlocale() instead.
> 'zh_CN'
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 🤔
> ```

我觉得目前问题还是在这里

**Comment by 2044-space-elevator** [comment]
> > ```python
> > ```python
> > Python 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)] on win32
> > Type "help", "copyright", "credits" or "license" for more information.
> > >>> import locale
> > >>> locale.getlocale()[0]
> > 'Chinese (Simplified)_China'
> > >>> locale.getdefaultlocale()[0]
> > <stdin>:1: DeprecationWarning: 'locale.getdefaultlocale' is deprecated and slated for removal in Python 3.15. Use setlocale(), getencoding() and getlocale() instead.
> > 'zh_CN'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 🤔
> 
> 我觉得目前问题还是在这里

问题是我测试过了环境变量的返回正常。应该是 pip 装库的时候没有执行 `.mo` 的下载。

**Comment by Rickyxrc** [comment]
> 问题是我测试过了环境变量的返回正常。应该是 pip 装库的时候没有执行 `.mo` 的下载。

mo文件是打包在whl里面的，请使用zip解压缩文件解包下载的对应版本的pypi包确认一下。
